### PR TITLE
CILG 7 minutes

### PR DESCRIPTION
**Pull request by austinfrey**

### CODE REVIEW

**Review by mycognosist — APPROVED** [review]
Looks good to me @austinfrey . Thanks for creating the new org! I'm stoked that we have a home :)

**Comment by arj03** [comment]
Hey Austin and others :) 

Sorry to have dropped the ball on the last meetings, I have been extremely busy and because of this I was sick in bed saturday. I really wanted to have joined the last meeting. I'll just say that it's so great to see the this going forward, I have been reading the notes from the meetings. I hope to have some time in the future to contribute however I can.

**Comment by austinfrey** [comment]
thanks for the review @mycognosist 

@arj03 hope the day of rest served you well and you're feeling better!

**Comment by arj03** [comment]
Thanks @austinfrey, I feel better today

**Pull request merged**
